#!/bin/bash
                                                                                                                                                                                  
for i in {1..64}
do
    filename=/work/clas12/jsalvg/RGA-Analysis/inb/NP/submit_ref_${i}
    echo $i
    echo "#!/bin/bash" >> ${filename}
    echo "#SBATCH --account=clas12" >> ${filename}
    echo "#SBATCH --partition=production" >> ${filename}
    echo "#SBATCH --job-name=NP_ref_$i" >> ${filename}
    echo "#SBATCH --constraint=general" >> ${filename}
    echo "#SBATCH --mail-user=jsalvg@jlab.org" >> ${filename}
    echo "#SBATCH --output=/work/clas12/jsalvg/RGA-Analysis/inb/NP/Logs/log_ref_$i.txt" >> ${filename}
    echo "#SBATCH --error=/work/clas12/jsalvg/RGA-Analysis/inb/NP/Errors/err_ref_$i.txt" >> ${filename}
    echo "#SBATCH --time=48:00:00" >> ${filename}
    echo "#SBATCH --gres=disk:5000" >> ${filename}
    echo "#SBATCH --ntasks=1" >> ${filename}
    echo "#SBATCH --mem-per-cpu=2000" >> ${filename}
    echo "/work/clas12/jsalvg/RGA-Analysis/inb/NP/Simu_Builder_ref $i" >> ${filename}
    sbatch ${filename} 
    
done 




