#!/bin/bash

for i in {1..94}
#for i in 67
do
    filename=/work/clas12/jsalvg/pass2_RGA-Analysis/inb/P_BSA/ssubmit_${i}
    echo $i
    echo "#!/bin/bash" >> ${filename}
    echo "#SBATCH --account=clas12" >> ${filename}
    echo "#SBATCH --partition=production" >> ${filename}
    echo "#SBATCH --job-name=P_Max_$i" >> ${filename}
    echo "#SBATCH --mail-user=jsalvg@jlab.org" >> ${filename}
    echo "#SBATCH --output=/work/clas12/jsalvg/pass2_RGA-Analysis/inb/P_BSA/Logs/log_$i.txt" >> ${filename}
    echo "#SBATCH --error=/work/clas12/jsalvg/pass2_RGA-Analysis/inb/P_BSA/Errors/err_$i.txt" >> ${filename}
    echo "#SBATCH --time=8:00:00" >> ${filename}
    echo "#SBATCH --gres=disk:5000" >> ${filename}
    echo "#SBATCH --ntasks=1" >> ${filename}
    echo "#SBATCH --mem-per-cpu=2000" >> ${filename}
    echo "/work/clas12/jsalvg/pass2_RGA-Analysis/inb/P_BSA/Simu_Builder $i" >> ${filename}
    sbatch ${filename} 
    
done 




