#!/bin/bash
                                                                                                                                                                                  
for i in {1..64}
do
    filename=/work/clas12/jsalvg/RGA-Analysis/inb/P/submit_${i}
    echo $i
    echo "#!/bin/bash" >> ${filename}
    echo "#SBATCH --account=clas12" >> ${filename}
    echo "#SBATCH --partition=production" >> ${filename}
    echo "#SBATCH --job-name=P_Max_$i" >> ${filename}
    echo "#SBATCH --mail-user=jsalvg@jlab.org" >> ${filename}
    echo "#SBATCH --output=/work/clas12/jsalvg/RGA-Analysis/inb/P/Logs/log_$i.txt" >> ${filename}
    echo "#SBATCH --error=/work/clas12/jsalvg/RGA-Analysis/inb/P/Errors/err_$i.txt" >> ${filename}
    echo "#SBATCH --time=23:00:00" >> ${filename}
    echo "#SBATCH --gres=disk:5000" >> ${filename}
    echo "#SBATCH --ntasks=1" >> ${filename}
    echo "#SBATCH --mem-per-cpu=2000" >> ${filename}
    echo "/work/clas12/jsalvg/RGA-Analysis/inb/P/Simu_Builder $i" >> ${filename}
    sbatch ${filename} 
    
done 




