#!/bin/bash
                                                                                                                                                                                  
for i in {1..64}
do
    filename=/work/clas12/jsalvg/RGA-Analysis/outb/NP/submit_FD_${i}
    echo $i
    echo "#!/bin/bash" >> ${filename}
    echo "#SBATCH --account=clas12" >> ${filename}
    echo "#SBATCH --partition=production" >> ${filename}
    echo "#SBATCH --job-name=NP_FD_$i" >> ${filename}
    echo "#SBATCH --constraint=general" >> ${filename}
    echo "#SBATCH --mail-user=jsalvg@jlab.org" >> ${filename}
    echo "#SBATCH --output=/work/clas12/jsalvg/RGA-Analysis/outb/NP/Logs/log_FD_$i.txt" >> ${filename}
    echo "#SBATCH --error=/work/clas12/jsalvg/RGA-Analysis/outb/NP/Errors/err_FD_$i.txt" >> ${filename}
    echo "#SBATCH --time=24:00:00" >> ${filename}
    echo "#SBATCH --gres=disk:5000" >> ${filename}
    echo "#SBATCH --ntasks=1" >> ${filename}
    echo "#SBATCH --mem-per-cpu=2000" >> ${filename}
    echo "/work/clas12/jsalvg/RGA-Analysis/outb/NP/Simu_Builder_FD $i" >> ${filename}
    sbatch ${filename} 
    
done 




